### ISSUE TITLE
On Windows, when testing agent, get "Cannot import name 'bullet_client' error

### ISSUE THREAD

**Issue by rfernand2** [benelot/pybullet-gym#38]
Seems to be version mismatch between latest pybullet-gym and pybullet 2.6.2.  Which version of pybullet **should** be used with pybullet-gym?

When I run the example for testing MuJoCo humaniod agent, I get the following error:

**pybullet build time: Jan  2 2020 14:03:15
current_dir=c:\anaconda3\envs\bulletgym\lib\site-packages\pybullet_envs\bullet
Traceback (most recent call last):
  File "./openai_gym.py", line 219, in <module>
    main()
  File "./openai_gym.py", line 113, in main
    visualize=args.visualize
  File "c:\anaconda3\envs\bulletgym\lib\site-packages\tensorforce\contrib\openai_gym.py", line 50, in __init__
    self.gym = gym.make(gym_id)  # Might raise gym.error.UnregisteredEnv or gym.error.DeprecatedEnv
  File "c:\github\gym\gym\envs\registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "c:\github\gym\gym\envs\registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "c:\github\gym\gym\envs\registration.py", line 58, in make
    cls = load(self.entry_point)
  File "c:\github\gym\gym\envs\registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "c:\anaconda3\envs\bulletgym\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\github\pybullet-gym\pybulletgym\envs\mujoco\envs\locomotion\humanoid_env.py", line 1, in <module>
    from pybulletgym.envs.mujoco.envs.locomotion.walker_base_env import WalkerBaseMuJoCoEnv
  File "c:\github\pybullet-gym\pybulletgym\envs\mujoco\envs\locomotion\walker_base_env.py", line 1, in <module>
    from pybulletgym.envs.mujoco.envs.env_bases import BaseBulletEnv
  File "c:\github\pybullet-gym\pybulletgym\envs\mujoco\envs\env_bases.py", line 4, in <module>
    from pybullet_envs.bullet import bullet_client
ImportError: cannot import name 'bullet_client'**

**Comment by rfernand2** [comment]
pybullet version 2.5.9 fixes this error.  Suggest the following commands:

- pip uninstall pybullet
- pip install pybullet==2.5.9
