### ISSUE TITLE
Which version of gym does this lib support?

### ISSUE THREAD

**Issue by billwang485** [benelot/pybullet-gym#77]
Traceback (most recent call last):
  File " ", line 9, in <module>                                                                               
    import pybullet_envs
  File " /lib/python3.9/site-packages/pybullet_envs/__init__.py", line 14, in <module>                                                   
    register(
  File " /lib/python3.9/site-packages/pybullet_envs/__init__.py", line 6, in register                                                    
    if id in registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'

I met this bug when trying to run code in "AntBulletEnv-v0" environment, so I want to ask about the dependency of this lib.

**Comment by wesleyyang1109** [comment]
I'm also having the same issue, have you solved it?
